name: "AI Proxy Router"
description: "Quản lý xoay vòng API Key và đăng nhập OpenAI Codex OAuth trực tiếp. Tự động định tuyến Text/Vision và theo dõi Analytics."
version: "1.6.0"
slug: "ai_proxy_router"
init: false
arch:
  - aarch64
  - amd64
panel_icon: mdi:robot-outline
panel_title: "AI Proxy"
ingress: true
ingress_port: 1236
ports:
  1236/tcp: 1236
map:
  - config:rw
options: {}
schema: {}
hassio_api: true
image: "ghcr.io/trankhanhduy2929-beep/ai_proxy_router-{arch}"
